/* Integração SST — carregamento robusto, sem travar a tela inicial */
(()=>{
'use strict';
const VERSION='20260903-22';
window.SSTAppModules=window.SSTAppModules||{};
function load(src){return new Promise((resolve,reject)=>{if(src==='sst-modulos.js'&&typeof window.openSSTModule==='function')return resolve(true);const s=document.createElement('script');s.src='./'+src+'?v='+VERSION+'&t='+Date.now();s.async=false;s.onload=()=>resolve(true);s.onerror=()=>reject(new Error(src));document.head.appendChild(s)})}
function fallback(type){
 const names={seg:['🦺','Inspeção de Segurança','Condições e irregularidades'],machine:['⚙️','Máquinas e Equipamentos','Checklist NR-12'],epi:['🧤','Inspeção de EPI','Controle e conformidade'],accident:['⚠️','Investigação de Acidente','Registro e causas'],report:['📋','Relatório de Inspeção','Irregularidade e melhoria']};
 const n=names[type]||names.seg;
 let old=document.getElementById('sst-fallback'); if(old)old.remove();
 const o=document.createElement('div');o.id='sst-fallback';o.style='position:fixed;inset:0;z-index:10000;background:#f1f5f9;overflow:auto';
 o.innerHTML='<div style="position:sticky;top:0;z-index:2;background:linear-gradient(135deg,#991b1b,#dc2626);color:#fff;padding:16px"><div style="max-width:900px;margin:auto;display:flex;align-items:center;justify-content:space-between"><div><div style="font-size:20px;font-weight:900">'+n[0]+' '+n[1]+'</div><div style="font-size:12px">'+n[2]+' • OFFLINE</div></div><button id="sstFallbackClose" style="padding:10px 14px;border:0;border-radius:10px;font-weight:900">✕ Fechar</button></div></div><div style="max-width:900px;margin:auto;padding:14px"><div style="background:#fff;border-radius:16px;padding:16px;box-shadow:0 2px 12px #0001"><div style="background:#fee2e2;color:#991b1b;padding:10px;border-radius:9px;margin-bottom:12px"><b>Modo de contingência ativado.</b><br>O módulo abriu sem depender do carregamento externo.</div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px"><label><b>Empresa</b><input id="sf-company" value="TBM Têxtil" style="width:100%;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></label><label><b>Setor</b><input id="sf-sector" style="width:100%;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></label><label><b>Local</b><input id="sf-place" style="width:100%;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></label><label><b>Data</b><input id="sf-date" type="date" value="'+new Date().toISOString().slice(0,10)+'" style="width:100%;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></label></div><label style="display:block;margin-top:10px"><b>Descrição / irregularidade</b><textarea id="sf-desc" style="width:100%;min-height:110px;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></textarea></label><label style="display:block;margin-top:10px"><b>Sugestão de melhoria / ação</b><textarea id="sf-action" style="width:100%;min-height:90px;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></textarea></label><label style="display:block;margin-top:10px"><b>Inspetor</b><input id="sf-inspector" value="Jonatas Marques de Arruda" style="width:100%;padding:11px;margin-top:5px;border:1px solid #cbd5e1;border-radius:9px"></label><div id="sf-msg" style="display:none;padding:10px;border-radius:9px;margin-top:12px"></div><button id="sf-save" style="width:100%;margin-top:12px;padding:13px;border:0;border-radius:10px;background:#15803d;color:#fff;font-weight:900">💾 SALVAR INSPEÇÃO</button><button id="sf-print" style="width:100%;margin-top:8px;padding:13px;border:0;border-radius:10px;background:#b91c1c;color:#fff;font-weight:900">📄 GERAR RELATÓRIO / PDF</button></div></div>';
 document.body.appendChild(o);
 document.getElementById('sstFallbackClose').onclick=()=>o.remove();
 const data=()=>({id:Date.now(),type,title:n[1],company:document.getElementById('sf-company').value,sector:document.getElementById('sf-sector').value,place:document.getElementById('sf-place').value,date:document.getElementById('sf-date').value,description:document.getElementById('sf-desc').value,action:document.getElementById('sf-action').value,inspector:document.getElementById('sf-inspector').value});
 document.getElementById('sf-save').onclick=()=>{localStorage.setItem('sst_fallback_'+Date.now(),JSON.stringify(data()));const m=document.getElementById('sf-msg');m.style.display='block';m.style.background='#dcfce7';m.style.color='#166534';m.textContent='✅ Inspeção salva no aparelho.'};
 document.getElementById('sf-print').onclick=()=>{const x=data(),w=window.open('','_blank');if(!w){alert('Permita pop-ups para gerar o relatório.');return}w.document.write('<html><head><meta charset="utf-8"><title>'+n[1]+'</title><style>body{font-family:Arial;margin:35px}h1{border-bottom:3px solid #b91c1c;padding-bottom:10px}.box{line-height:1.8;border:1px solid #ddd;padding:15px} .sig{margin-top:70px;display:flex;gap:80px}.line{border-top:1px solid #111;width:240px;padding-top:5px}</style></head><body><h1>'+n[0]+' '+n[1]+'</h1><div class="box"><b>Data:</b> '+x.date+'<br><b>Empresa:</b> '+x.company+'<br><b>Setor:</b> '+x.sector+'<br><b>Local:</b> '+x.place+'<br><b>Descrição / irregularidade:</b><br>'+x.description.replace(/\n/g,'<br>')+'<br><b>Ação / melhoria:</b><br>'+x.action.replace(/\n/g,'<br>')+'<br><b>Inspetor:</b> '+x.inspector+'</div><div class="sig"><div class="line">'+x.inspector+'<br>Inspetor</div><div class="line">Responsável / Acompanhante</div></div><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>');w.document.close()};
}
async function ensure(){if(typeof window.openSSTModule==='function')return true;try{await load('sst-modulos.js')}catch(e){console.warn('SST externo indisponível; usando contingência',e)}return typeof window.openSSTModule==='function'}
function bind(){const map={startSafety:'seg',startMachine:'machine',startEpi:'epi',startAccident:'accident',startReport:'report'};for(const [id,type] of Object.entries(map)){const b=document.getElementById(id);if(!b||b.dataset.sstBound==='1')continue;b.dataset.sstBound='1';b.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();if(await ensure()){window.openSSTModule(type)}else{fallback(type)}})}}
window.SSTAppModules.ready=ensure();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
[300,1000,2500,5000].forEach(ms=>setTimeout(bind,ms));
})();