/* MASTER FIX — estabilização, Firebase, histórico e PDF */
(()=>{
'use strict';
const CFG={apiKey:'AIzaSyBFOJOxX59k1dfZbOauv4zjkh_qhynuLuQ',authDomain:'app-inspecao-sst-79aa6.firebaseapp.com',projectId:'app-inspecao-sst-79aa6',storageBucket:'app-inspecao-sst-79aa6.firebasestorage.app',messagingSenderId:'992254064215',appId:'1:992254064215:web:ffa5f1c463b444d8479512',measurementId:'G-ZQ0ZT0YVPE'};
let cloudReady=false,fs=null;
const $=id=>document.getElementById(id);
function script(src){return new Promise((ok,no)=>{if(document.querySelector('script[src="'+src+'"]'))return ok();const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function css(){if($('masterFixCSS'))return;const s=document.createElement('style');s.id='masterFixCSS';s.textContent=`.premium-home{position:relative;overflow:hidden;background:linear-gradient(145deg,#fff,#f8fafc);border:1px solid #e2e8f0;border-radius:28px;padding:28px 20px;box-shadow:0 18px 55px #0f172a18}.welcome-badge{display:inline-block;background:#fee2e2;color:#991b1b;padding:7px 12px;border-radius:999px;font-size:11px;font-weight:900}.today-card{background:#111827;color:#fff;border-radius:18px;padding:15px;text-align:center;margin:18px 0}.today-label{font-size:10px;text-transform:uppercase;letter-spacing:1.5px;opacity:.65}.today-date{font-size:18px;font-weight:900;margin-top:5px}.today-time{font-size:12px;opacity:.75}.choice-title{font-size:17px;font-weight:900;margin:18px 0 10px}.inspection-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.inspection-tile{min-height:135px;border-radius:19px;color:#fff;text-align:left;padding:16px;display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 10px 25px #0f172a20}.icon3d{font-size:31px}.inspection-tile strong{display:block;font-size:14px}.inspection-tile span{display:block;font-size:10px;opacity:.78;margin-top:3px}.inspection-tile.safety{background:linear-gradient(145deg,#0f172a,#475569)}.inspection-tile.machine{background:linear-gradient(145deg,#1d4ed8,#60a5fa)}.inspection-tile.epi{background:linear-gradient(145deg,#047857,#34d399)}.inspection-tile.accident{background:linear-gradient(145deg,#92400e,#f59e0b)}.inspection-tile.reporttile{background:linear-gradient(145deg,#581c87,#a855f7)}.premium-history{width:100%;margin-top:12px;background:#fff;border:1px solid #dbe2ea}.premium-status{text-align:center;color:#64748b;font-size:11px;margin-top:12px}.premium-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-right:5px}.reportWrap{background:#e9edf3;padding:18px}.report{background:#fff}.reportSection{break-inside:auto}.reportFooter{font-size:8px}.masterLogo{width:86px;height:58px;border:2px solid #374151;border-radius:10px;display:flex;flex-direction:column;align-items:center;justify-content:center;margin:0 auto 7px;color:#374151;background:#fff}.masterLogo b{font-size:24px;line-height:1}.masterLogo span{font-size:8px;letter-spacing:3px;margin-top:3px}`;document.head.appendChild(s)}
function fixLogo(){const h=document.querySelector('.tbmLogo');if(h)h.outerHTML='<div class="masterLogo"><b>TBM</b><span>TÊXTIL</span></div>'}
async function firebase(){try{await script('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await script('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js');await script('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js');if(!firebase.apps.length)firebase.initializeApp(CFG);const a=firebase.auth();if(!a.currentUser)await a.signInAnonymously();fs=firebase.firestore();cloudReady=true;setStatus('CLOUD ATIVO');await pull();await push();setInterval(()=>push().catch(()=>{}),15000)}catch(e){console.warn('Firebase:',e);cloudReady=false;setStatus('LOCAL / OFFLINE')}}
function setStatus(t){const n=$('net');if(n)n.textContent=t;const c=document.querySelector('.premium-status');if(c)c.innerHTML='<span class="premium-dot"></span> '+t+' • dados persistentes'}
function openStore(dbName,store){return new Promise((ok,no)=>{const r=indexedDB.open(dbName);r.onsuccess=()=>{const d=r.result;if(!d.objectStoreNames.contains(store))return ok([]);const q=d.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>ok(q.result||[]);q.onerror=()=>no(q.error)};r.onerror=()=>no(r.error)})}
async function localAll(){const a=await openStore('InspecaoIncendioPremium','inspecoes');const b=await openStore('SSTInspecoes','registros');const map=new Map();[...a,...b].forEach(x=>{if(x?.id)map.set(String(x.id),x)});return [...map.values()]}
async function localPut(x){return new Promise((ok,no)=>{const r=indexedDB.open('InspecaoIncendioPremium',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('inspecoes'))r.result.createObjectStore('inspecoes',{keyPath:'id'})};r.onsuccess=()=>{const q=r.result.transaction('inspecoes','readwrite').objectStore('inspecoes').put(x);q.onsuccess=ok;q.onerror=()=>no(q.error)};r.onerror=()=>no(r.error)})}
function safe(x){const y=JSON.parse(JSON.stringify(x));let raw=JSON.stringify(y);if(raw.length>900000){if(Array.isArray(y.photos))y.photos=[];if(Array.isArray(y.equipments))y.equipments=y.equipments.map(e=>({...e,photos:[]}));raw=JSON.stringify(y);if(raw.length>900000)y.sig1='';if(raw.length>900000)y.sig2='';if(raw.length>900000)y.signature='';}return y}
async function push(){if(!cloudReady)return;for(const x of await localAll()){try{await fs.collection('inspections').doc(String(x.id)).set({...safe(x),cloudUpdatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(e){console.warn('cloud write',e)}}}
async function pull(){if(!cloudReady)return;try{const snap=await fs.collection('inspections').get();for(const d of snap.docs){const x=d.data();delete x.cloudUpdatedAt;if(x.id)await localPut(x)}}catch(e){console.warn('cloud read',e)}}
function bindButtons(){const fire=$('start');if(fire&&!fire.dataset.master){fire.dataset.master=1;fire.onclick=e=>{e.preventDefault();if(typeof window.newInspection==='function')window.newInspection();else location.reload()}}const hist=$('hist');if(hist&&!hist.dataset.master){hist.dataset.master=1;hist.onclick=async()=>{if(typeof window.getAll==='function'){try{const a=await getAll();$('historyList').innerHTML=a.length?a.map(x=>'<div class="card"><b>Relatório '+String(x.id).slice(-6)+'</b><br>'+esc(x.company==='Outro'?x.companyOther:x.company)+'<br>'+new Date(x.created).toLocaleDateString('pt-BR')+' • '+x.equipments.length+' equipamento(s)<br><button class="btn primary" type="button" data-open="'+x.id+'">📄 Abrir relatório</button> <button class="btn danger" type="button" data-del="'+x.id+'">🗑️ Excluir</button></div>').join(''):'Nenhuma inspeção salva.';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{const x=(await getAll()).find(z=>String(z.id)===b.dataset.open);if(x){current=x;$('reportContent').innerHTML=reportHTML(x);show('report')}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir esta inspeção?')){await del(Number(b.dataset.del));$('hist').click()}});show('history')}catch(e){await historyFallback()}}else await historyFallback()}};const pb=$('print');if(pb&&!pb.dataset.master){pb.dataset.master=1;pb.onclick=generatePDF}}
async function historyFallback(){const list=await localAll();if(!$('historyList'))return;$('historyList').innerHTML=list.length?list.sort((a,b)=>Number(b.id)-Number(a.id)).map(x=>`<div class="card"><b>Relatório ${String(x.id).slice(-8)}</b><br>${x.company||x.title||'Inspeção'}<br><span class="small">${new Date(x.created||x.date||Date.now()).toLocaleString('pt-BR')}</span><br><button class="btn primary" data-mf-open="${x.id}">📄 Abrir relatório</button></div>`).join(''):'Nenhuma inspeção salva.';document.querySelectorAll('[data-mf-open]').forEach(b=>b.onclick=async()=>{const x=list.find(z=>String(z.id)===b.dataset.mfOpen);if(x&&typeof window.reportHTML==='function'){window.current=x;$('reportContent').innerHTML=window.reportHTML(x);if(typeof window.show==='function')window.show('report')}});if(typeof window.show==='function')window.show('history')}
async function generatePDF(){const content=$('reportContent');if(!content)return;if(!window.html2pdf){window.print();return}try{toast('⏳ Preparando PDF...');const opt={margin:[7,7,9,7],filename:`Relatorio-${String(window.current?.id||Date.now()).slice(-8)}.pdf`,image:{type:'jpeg',quality:.96},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}};const blob=await html2pdf().set(opt).from(content).outputPdf('blob');const file=new File([blob],opt.filename,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'Relatório de Inspeção SST',text:'Relatório profissional de inspeção',files:[file]});return}catch(e){if(e.name==='AbortError')return}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=opt.filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);toast('✅ PDF gerado com sucesso','success')}catch(e){console.error(e);window.print()}}
function toast(msg,type){let t=$('masterToast');if(!t){t=document.createElement('div');t.id='masterToast';t.style='position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:99999;background:#111827;color:#fff;padding:12px 16px;border-radius:12px;font-weight:800;font-size:12px;box-shadow:0 15px 40px #0004';document.body.appendChild(t)}t.textContent=msg;t.style.background=type==='success'?'#166534':type==='error'?'#991b1b':'#111827';clearTimeout(t._x);t._x=setTimeout(()=>t.remove(),3600)}
window.SSTMasterFix={push,pull,isCloudReady:()=>cloudReady};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{css();bindButtons();fixLogo();firebase()});else{css();bindButtons();fixLogo();firebase()}
[500,1500,3000,6000].forEach(ms=>setTimeout(bindButtons,ms));
})();
