(()=>{
'use strict';
const LOGO='Têxtil Bezerra de Menezes 2.jpeg';
const LIGHT=['Luminária fixada corretamente?','Bateria/Teste funcionando?','Cabos bem isolados?'];
const ALARM=['Acionador manual desobstruído?','Sinal sonoro audível?','Painel central sem erro?'];
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fmt(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
const extra=()=>window.__tbmExtra||[];const setExtra=a=>window.__tbmExtra=a||[];
function css(){if($('tbmV11'))return;const s=document.createElement('style');s.id='tbmV11';s.textContent=`
.logo{height:58px!important;width:auto!important;max-width:210px!important;object-fit:contain!important;background:#fff!important;padding:5px!important;border-radius:10px!important}.reportLogo{width:105px!important;height:78px!important;object-fit:contain!important;background:#fff!important;padding:3px!important;border-radius:6px!important}.premium-extra{border-left:4px solid #8b1018!important}.premium-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.premium-meta label{display:block;font-size:11px;font-weight:900;margin-bottom:5px}.premium-meta input,.premium-extra select{width:100%;padding:9px;border:1px solid #2a3642;border-radius:9px;background:#101820;color:#f4f6f8}.premium-extra .check{margin:8px 0}.reportPage{font-family:Arial,Helvetica,sans-serif!important;color:#111!important;background:#fff!important}.reportPage .rtable tbody tr:nth-child(even){background:#f8fafc}.reportPage .rtable tr,.reportPage .rphotos figure,.reportPage .rsigs,.reportPage .rsig{break-inside:avoid;page-break-inside:avoid}.reportPage .rphotos{grid-template-columns:repeat(2,1fr)!important}@media(max-width:560px){.logo{height:52px!important;max-width:180px!important}.premium-meta{grid-template-columns:1fr}.reportPage .rphotos{grid-template-columns:1fr 1fr!important}}`;document.head.appendChild(s)}
function logo(){document.querySelectorAll('img.logo,img.reportLogo').forEach(i=>{i.src=LOGO;i.alt='Têxtil Bezerra de Menezes';i.loading='eager'})}
function compress(f){return new Promise((ok,no)=>{const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{let w=i.naturalWidth,h=i.naturalHeight,sc=Math.min(1,800/Math.max(w,h));w=Math.max(1,Math.round(w*sc));h=Math.max(1,Math.round(h*sc));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d',{alpha:false}).drawImage(i,0,0,w,h);URL.revokeObjectURL(u);c.toBlob(b=>b?ok(new File([b],f.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'})):no(),'image/jpeg',.76)};i.onerror=no;i.src=u})}
function photo(){const i=$('photoInput');if(!i||i.dataset.tbm)return;i.dataset.tbm='1';const old=i.onchange;i.onchange=async e=>{const fs=[...(e.target.files||[])];if(!fs.length)return;try{const d=new DataTransfer();for(const f of fs)if(f.type.startsWith('image/'))d.items.add(await compress(f));Object.defineProperty(i,'files',{configurable:true,value:d.files});if(typeof old==='function')old.call(i,{target:i})}catch(x){console.error(x);alert('Não foi possível processar a foto.')}finally{i.value=''}}}
function photoButtons(){const i=$('photoInput');if(!i||document.querySelector('.photoTools'))return;const t=document.createElement('div');t.className='photoTools';const a=document.createElement('button'),b=document.createElement('button');a.type=b.type='button';a.className=b.className='btn secondary';a.textContent='📷 TIRAR FOTO';b.textContent='🖼️ ESCOLHER DA GALERIA';a.onclick=()=>{i.setAttribute('capture','environment');i.click()};b.onclick=()=>{i.removeAttribute('capture');i.click();setTimeout(()=>i.setAttribute('capture','environment'),300)};t.append(a,b);i.insertAdjacentElement('afterend',t)}
const oldAdd=window.addEquipment;window.addEquipment=function(k){if(k==='light'||k==='alarm'){const a=extra();a.push({kind:k,status:'PENDENTE',patrimonio:'',localizacao:'',obs:'',checks:(k==='light'?LIGHT:ALARM).map(()=> 'PENDENTE')});setExtra(a);window.renderEquipment?.();window.scheduleSave?.();return}return oldAdd?.(k)};
const oldRender=window.renderEquipment;window.renderEquipment=function(){oldRender?.();const l=$('equipmentList');if(!l)return;l.querySelectorAll('.premium-extra').forEach(x=>x.remove());extra().forEach((e,n)=>{const qs=e.kind==='light'?LIGHT:ALARM,t=document.createElement('div');t.className='equipment premium-extra';t.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px"><h3>${e.kind==='light'?'💡 Iluminação de Emergência':'🚨 Sirene / Alarme'} #${n+1}</h3><button type="button" class="btn danger no-print" data-tbm-del="${n}" style="padding:7px 9px">Excluir</button></div><div class="premium-meta"><div><label>Patrimônio (opcional)</label><input data-tbm-e="${n}" data-tbm-k="patrimonio" value="${esc(e.patrimonio)}"></div><div><label>Localização</label><input data-tbm-e="${n}" data-tbm-k="localizacao" value="${esc(e.localizacao)}"></div></div><div class="title" style="font-size:13px;margin:12px 0 7px">Checklist</div>${qs.map((q,j)=>`<div class="check"><div class="checkrow"><b style="font-size:12px">${j+1}. ${esc(q)}</b><select data-tbm-e="${n}" data-tbm-q="${j}"><option ${e.checks[j]==='CONFORME'?'selected':''}>CONFORME</option><option ${e.checks[j]==='NÃO CONFORME'?'selected':''}>NÃO CONFORME</option><option ${e.checks[j]==='PENDENTE'?'selected':''}>PENDENTE</option><option ${e.checks[j]==='N/A'?'selected':''}>N/A</option></select></div></div>`).join('')}<div class="field" style="margin-top:10px"><label>Observações</label><textarea data-tbm-e="${n}" data-tbm-k="obs">${esc(e.obs)}</textarea></div>`;l.appendChild(t)})};
function buttons(){const h=$('addHid');if(!h||$('addIluminacao'))return;for(const [id,text,k] of [['addIluminacao','💡 Iluminação','light'],['addSirene','🚨 Sirene/Alarme','alarm']]){const b=document.createElement('button');b.id=id;b.type='button';b.className=h.className;b.textContent=text;b.onclick=()=>window.addEquipment(k);h.insertAdjacentElement('afterend',b);h=b}}
const oldPut=window.idbPut;if(oldPut&&!window.__tbmPut){window.__tbmPut=1;window.idbPut=async x=>{const y=JSON.parse(JSON.stringify(x));if(extra().length)y.equipment=[...(y.equipment||[]),...extra().map(e=>({kind:e.kind,status:e.status,patrimonio:e.patrimonio,localizacao:e.localizacao,obs:e.obs,premiumChecks:e.checks}))];return oldPut(y)}}
const oldCloud=window.cloudSafe;if(oldCloud&&!window.__tbmCloud){window.__tbmCloud=1;window.cloudSafe=x=>{const y=oldCloud(x);if(extra().length)y.equipment=[...(y.equipment||[]),...extra().map(e=>({kind:e.kind,status:e.status,patrimonio:e.patrimonio,localizacao:e.localizacao,obs:e.obs,premiumChecks:e.checks}))];return y}}
const oldReset=window.reset;if(oldReset&&!window.__tbmReset){window.__tbmReset=1;window.reset=k=>{setExtra([]);return oldReset(k)}}
const oldGet=window.idbGet;if(oldGet&&!window.__tbmGet){window.__tbmGet=1;window.idbGet=async id=>{const x=await oldGet(id);if(x)setExtra((x.equipment||[]).filter(e=>e.kind==='light'||e.kind==='alarm').map(e=>({kind:e.kind,status:e.status||'PENDENTE',patrimonio:e.patrimonio||'',localizacao:e.localizacao||'',obs:e.obs||'',checks:e.premiumChecks||e.checks||[]})));return x}}
function events(){if(document.body.dataset.tbm)return;document.body.dataset.tbm='1';document.addEventListener('input',e=>{const i=e.target.dataset.tbmE,k=e.target.dataset.tbmK;if(i===undefined||!k)return;const a=extra();if(a[+i]){a[+i][k]=e.target.value;setExtra(a);window.scheduleSave?.()}});document.addEventListener('change',e=>{const i=e.target.dataset.tbmE;if(i===undefined||e.target.dataset.tbmQ===undefined)return;const a=extra();if(a[+i]){a[+i].checks[+e.target.dataset.tbmQ]=e.target.value;setExtra(a);window.scheduleSave?.()}});document.addEventListener('click',e=>{const b=e.target.closest('[data-tbm-del]');if(!b)return;const a=extra();a.splice(+b.dataset.tbmDel,1);setExtra(a);window.renderEquipment?.();window.scheduleSave?.()})}
function reportPatch(){if(typeof window.reportHTML!=='function'||window.__tbmReport)return;window.__tbmReport=1;const old=window.reportHTML;window.reportHTML=x=>{let h=old(x);h=h.replaceAll('src="icon.svg"',`src="${LOGO}"`);const ex=(x.equipment||[]).filter(e=>e.kind==='light'||e.kind==='alarm');if(ex.length){let n=(x.equipment||[]).filter(e=>e.kind==='ext'||e.kind==='hid').length;ex.forEach((e,i)=>{const label=e.kind==='light'?'Iluminação de Emergência':'Sirene / Alarme';h=h.replace(`>Hidrante #${n+i+1}<`,`>${label} #${i+1}<`);});}return h};const oldPdf=window.makePdf;if(typeof oldPdf==='function'&&!window.__tbmPdf){window.__tbmPdf=1;window.makePdf=async share=>{const c=$('reportContent');if(c){const imgs=[...c.querySelectorAll('img')];await Promise.all(imgs.map(im=>im.complete?Promise.resolve():new Promise(r=>{im.onload=im.onerror=r})))}return oldPdf(share)}}}
function setup(){css();logo();buttons();photo();photoButtons();events();reportPatch();setTimeout(()=>{logo();buttons();photo();photoButtons();reportPatch()},700);setTimeout(()=>{logo();buttons();photo();photoButtons()},1800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();