const CACHE='inspecao-sst-demo-v93';
const CORE=['./','./index.html','./icon.svg','./icon-192.png','./icon-512.png','./Têxtil Bezerra de Menezes 2.jpeg','./manifest.json','./pwa-install-fix.js','./premium.css','./premium.js','./integracao-modulos.js','./local-history.js','./extintor-enhancements.js','./sst-repair-loader.js','./global-pdf-preview.js','./solid-status-badges.js','./photo-multi-fix.js','./save-button-fix.js','./cnpj-autofill.js','./fire-checklist-split.js','./pt-altura.js','./pt-contrast-fix.js','./pt-share-preview-fix.js','./pt-renovacao-nr35.js','./premium-ux.js','./mobile-performance-fix.js','./mobile-interaction-fix.js','./email-relatorio-auto.js','./nr24-module.js','./training-attendance-module.js','./training-attendance-refinement.js','./accident-injury-module.js','./accident-diagnosis-conditional.js','./pdf-global-standard.js','./pdf-filename-global.js','./pdf-final-fix.js','./pdf-layout-fix.js','./demo-client-mode.js','./demo-access-gate.js','./delete-draft.js'];
const EXTERNAL=[
 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js',
 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js',
 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js',
 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js',
 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(async cache=>{for(const url of CORE){try{const r=await fetch(url+'?v=93',{cache:'no-store'});if(r.ok)await cache.put(url,r)}catch(e){}}for(const url of EXTERNAL){try{const r=await fetch(url,{cache:'no-store',mode:'cors'});if(r.ok)await cache.put(url,r)}catch(e){}}}).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('inspecao-sst-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const u=new URL(event.request.url);const external=EXTERNAL.includes(u.href);if(external){event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(event.request,r.clone())).catch(()=>{});return r})));return}if(u.origin!==location.origin)return;event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(c=>c.put(event.request,response.clone())).catch(()=>{});return response}).catch(()=>{const clean=new Request(u.origin+u.pathname);return caches.match(event.request).then(r=>r||caches.match(clean)).then(r=>{if(r)return r;if(event.request.mode==='navigate')return caches.match('./index.html');return new Response('',{status:503,statusText:'Offline'})})}))});
